apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service-deployment
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: location-service
          image: ghcr.io/shreeraamg/microservices/location-service:0.0.3
          ports:
            - containerPort: 8070
          envFrom:
            - configMapRef:
                name: location-service-config
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: mongodb-uri
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8070
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8070
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
