apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service-deployment
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: location-service
          image: ghcr.io/shreeraamg/microservices/location-service:0.0.2
          ports:
            - containerPort: 8070
          envFrom:
            - configMapRef:
                name: location-service-config
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: mongodb-uri
