apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service-deployment
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: price-service
          image: ghcr.io/shreeraamg/microservices/price-service:0.0.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: price-service-config
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: mongodb-uri